[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
calculator = "32JfkcWscdvsJ65t1YxRz7L9xbCcXgcYEqbvL3cXy66c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ethan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
